theme: jekyll-theme-minimal
lsi: false
safe: true
incremental: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude:
  - scripts
  - vendor
  - Gemfile
baseurl: "/2025"
url: "https://rlbrew-workshop.github.io"
